import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { Connection } from '@xyflow/react';
import { nodeKinds, edgeKinds, newNode, validateDocument, mergeDocument, type ArchDocument, type ArchNode, type ArchEdge, type Diagram, type DiagramImport, type Revision, type Proposal } from '../core/model';
import { toUml, parseUml } from '../core/uml';
import { diffDocuments, stable, type Change } from '../core/diff';
import Canvas, { Markers } from './Canvas';
async function api<T>(url: string, body?: unknown): Promise<T> {
  const response = await fetch(`/api${url}`, body === undefined ? undefined : { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Atlas-Client': 'studio' }, body: JSON.stringify(body) });
  const result = await response.json(); if (!response.ok) throw new Error(result.error ?? 'Request failed'); return result;
}
function download(name: string, content: string, type = 'application/json') { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
const uid = (prefix: string) => `${prefix}_${crypto.randomUUID().slice(0, 8)}`;
type Selection = { kind: 'node' | 'edge' | 'import'; id: string } | null;
type Review = { before: ArchDocument; after: ArchDocument; label: string; rationale: string; proposal?: Proposal };
const date = (s: string) => new Date(s).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
export default function App() {
  const [head, setHead] = useState<Revision | null>(null); const [doc, setDoc] = useState<ArchDocument | null>(null); const [workspacePath, setWorkspacePath] = useState(''); const [mcpConfig, setMcpConfig] = useState<Record<string, unknown> | null>(null);
  const [diagramId, setDiagramId] = useState('overview'); const [selection, setSelection] = useState<Selection>(null);
  const [tab, setTab] = useState<'canvas' | 'uml' | 'json' | 'review'>('canvas'); const [source, setSource] = useState(''); const [sourceDirty, setSourceDirty] = useState(false);
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [remoteChanged, setRemoteChanged] = useState(false);
  const [history, setHistory] = useState<Omit<Revision, 'document'>[]>([]); const [proposals, setProposals] = useState<Omit<Proposal, 'document'>[]>([]);
  const [review, setReview] = useState<Review | null>(null); const [focus, setFocus] = useState<string>(); const [showLayout, setShowLayout] = useState(false);
  const [newKind, setNewKind] = useState<ArchNode['kind']>('component'); const [relationship, setRelationship] = useState<ArchEdge['kind']>('dependency');
  const [undo, setUndo] = useState<ArchDocument[]>([]); const [redo, setRedo] = useState<ArchDocument[]>([]);
  const [modal, setModal] = useState<'save' | 'new' | 'embed' | 'help' | 'mcp' | 'discard' | null>(null); const [input, setInput] = useState(''); const [embedTarget, setEmbedTarget] = useState(''); const [author, setAuthor] = useState('Designer');
  const importRef = useRef<HTMLInputElement>(null); const [codePreview, setCodePreview] = useState<{ path: string; startLine: number; endLine: number; code: string } | null>(null);
  const diagram = doc?.diagrams.find(d => d.id === diagramId) ?? doc?.diagrams[0];
  const dirty = !!head && !!doc && stable(head.document) !== stable(doc);
  const refreshMeta = useCallback(async () => { const [h, p] = await Promise.all([api<typeof history>('/history'), api<typeof proposals>('/proposals')]); setHistory(h); setProposals(p); }, []);
  const load = useCallback(async () => {
    const state = await api<Revision & { workspacePath: string; mcpConfig: Record<string, unknown> }>('/workspace'); setHead(state); setDoc(state.document); setWorkspacePath(state.workspacePath); setMcpConfig(state.mcpConfig); setRemoteChanged(false); setUndo([]); setRedo([]); setSourceDirty(false); setReview(null); await refreshMeta();
  }, [refreshMeta]);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  useEffect(() => { const timer = setInterval(() => { refreshMeta().catch(() => {}); api<Revision>('/workspace').then(r => setRemoteChanged(!!head && r.revision !== head.revision)).catch(() => {}); }, 4000); return () => clearInterval(timer); }, [head, refreshMeta]);
  useEffect(() => { if (notice) { const timer = setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timer); } }, [notice]);
  useEffect(() => { const handler = (e: BeforeUnloadEvent) => { if (dirty || sourceDirty) e.preventDefault(); }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty, sourceDirty]);
  useEffect(() => {
    if (!modal && !codePreview) return;
    const previous = document.activeElement as HTMLElement | null;
    const dialog = document.querySelector<HTMLElement>('[role="dialog"]');
    const focusable = () => Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), textarea:not(:disabled), select:not(:disabled), [tabindex="0"]') ?? []);
    if (dialog && !dialog.contains(document.activeElement)) focusable()[0]?.focus();
    const trap = (event: KeyboardEvent) => {
      if (event.key === 'Escape') { setModal(null); setCodePreview(null); }
      if (event.key !== 'Tab') return;
      const elements = focusable(); const first = elements[0]; const last = elements[elements.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); }
    };
    document.addEventListener('keydown', trap);
    return () => { document.removeEventListener('keydown', trap); previous?.focus(); };
  }, [modal, codePreview]);
  const run = async (fn: () => Promise<void>) => { setError(''); setBusy(true); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const edit = useCallback((next: ArchDocument) => { if (doc) setUndo(u => [...u.slice(-79), doc]); setDoc(next); setRedo([]); setError(''); }, [doc]);
  const editDiagram = (next: Diagram) => { if (doc && diagram) edit({ ...doc, diagrams: doc.diagrams.map(d => d.id === diagram.id ? next : d) }); };
  const navigate = useCallback((id: string) => { if (sourceDirty) { setError('Apply or discard your source edits before opening another diagram.'); return; } setDiagramId(id); setSelection(null); setFocus(undefined); }, [sourceDirty]);
  const expand = useCallback((id: string) => { if (doc && diagram) edit({ ...doc, diagrams: doc.diagrams.map(d => d.id === diagram.id ? { ...d, imports: d.imports.map(i => i.id === id ? { ...i, expanded: !i.expanded } : i) } : d) }); }, [doc, diagram, edit]);
  useEffect(() => { if (!sourceDirty && diagram) setSource(tab === 'json' ? JSON.stringify(diagram, null, 2) : toUml(diagram)); }, [diagram, sourceDirty, tab]);
  const switchTab = (next: typeof tab) => { if (sourceDirty) { setError('Apply or discard your source edits before changing views.'); return; } if (next === 'review') setReview(null); setTab(next); setError(''); };
  const changeSet = useMemo(() => doc && head ? diffDocuments(review?.before ?? head.document, review?.after ?? doc) : [], [doc, head, review]);
  const reviewDoc = review?.after ?? doc; const reviewBase = review?.before ?? head?.document;
  const reviewDiagram = reviewDoc?.diagrams.find(d => d.id === diagramId) ?? reviewBase?.diagrams.find(d => d.id === diagramId) ?? reviewDoc?.diagrams[0];
  const beforeDiagram = reviewBase?.diagrams.find(d => d.id === reviewDiagram?.id);
  const afterDiagram = reviewDoc?.diagrams.find(d => d.id === reviewDiagram?.id);
  const selectedNode = selection?.kind === 'node' ? diagram?.nodes.find(n => n.id === selection.id) : undefined;
  const selectedEdge = selection?.kind === 'edge' ? diagram?.edges.find(e => e.id === selection.id) : undefined;
  const selectedImport = selection?.kind === 'import' ? diagram?.imports.find(i => i.id === selection.id) : undefined;
  const updateNode = (patch: Partial<ArchNode>) => { if (diagram && selectedNode) editDiagram({ ...diagram, nodes: diagram.nodes.map(n => n.id === selectedNode.id ? { ...n, ...patch } : n) }); };
  const updateEdge = (patch: Partial<ArchEdge>) => { if (diagram && selectedEdge) editDiagram({ ...diagram, edges: diagram.edges.map(e => e.id === selectedEdge.id ? { ...e, ...patch } : e) }); };
  const updateImport = (patch: Partial<DiagramImport>) => { if (diagram && selectedImport) editDiagram({ ...diagram, imports: diagram.imports.map(i => i.id === selectedImport.id ? { ...i, ...patch } : i) }); };
  const removeSelection = () => { if (!diagram || !selection) return; editDiagram({ ...diagram, nodes: diagram.nodes.filter(n => n.id !== selection.id), imports: diagram.imports.filter(i => i.id !== selection.id), edges: diagram.edges.filter(e => e.id !== selection.id && e.source !== selection.id && e.target !== selection.id) }); setSelection(null); };
  const addNode = () => { if (!diagram) return; const n = newNode(uid(newKind), newKind, { x: (diagram.nodes.length % 4) * 310 + 40, y: Math.floor(diagram.nodes.length / 4) * 230 + 40 }); editDiagram({ ...diagram, nodes: [...diagram.nodes, n] }); setSelection({ kind: 'node', id: n.id }); };
  const connect = (c: Connection) => { if (!diagram || !c.source || !c.target || ![...diagram.nodes, ...diagram.imports].some(n => n.id === c.source) || ![...diagram.nodes, ...diagram.imports].some(n => n.id === c.target)) return; const id = uid('rel'); const next = { ...diagram, edges: [...diagram.edges, { id, source: c.source, target: c.target, kind: relationship, label: '', sourceMultiplicity: '', targetMultiplicity: '' }] }; try { validateDocument({ ...doc!, diagrams: doc!.diagrams.map(d => d.id === next.id ? next : d) }); editDiagram(next); setSelection({ kind: 'edge', id }); } catch (e) { setError((e as Error).message); } };
  const applySource = () => { try { if (!diagram || !doc) return; const next = tab === 'json' ? JSON.parse(source) : parseUml(source, diagram); if (next.id !== diagram.id) throw new Error('Keep the diagram ID unchanged. Create a new diagram to use a different ID.'); const candidate = validateDocument({ ...doc, diagrams: doc.diagrams.map(d => d.id === diagram.id ? next : d) }); edit(candidate); setSourceDirty(false); setNotice('Source applied to the diagram'); } catch (e) { setError((e as Error).message); } };
  const save = () => run(async () => { if (!doc || !head) return; const next = await api<Revision>('/save', { document: validateDocument(doc), baseRevision: head.revision, author, rationale: input }); setHead(next); setDoc(next.document); setUndo([]); setRedo([]); setRemoteChanged(false); setModal(null); setNotice('Revision saved'); await refreshMeta(); });
  const openProposal = (id: string) => run(async () => { if (sourceDirty) throw new Error('Apply or discard your source edits first'); const r = await api<{ proposal: Proposal; base: Revision }>(`/proposals/${id}`); setReview({ before: r.base.document, after: r.proposal.document, label: `Proposal by ${r.proposal.author}`, rationale: r.proposal.rationale, proposal: r.proposal }); setTab('review'); setFocus(undefined); });
  const compareHistory = (id: string) => run(async () => { if (sourceDirty) throw new Error('Apply or discard your source edits first'); const before = await api<Revision>(`/revisions/${id}`); setReview({ before: before.document, after: head!.document, label: `${date(before.createdAt)} → current revision`, rationale: before.rationale }); setTab('review'); });
  const reviewProposal = (action: 'accept' | 'reject') => run(async () => { if (!review?.proposal) return; if (action === 'accept' && dirty) throw new Error('Save or discard your local draft before accepting a proposal.'); await api(`/proposals/${review.proposal.id}/review`, { action }); if (action === 'accept') { await load(); setTab('canvas'); } else { setReview(null); await refreshMeta(); } setNotice(`Proposal ${action === 'accept' ? 'accepted' : 'rejected'}`); });
  const importFile = (file: File) => run(async () => { if (!doc) return; if (file.size > 5_000_000) throw new Error('Import is limited to 5 MB'); const content = JSON.parse(await file.text()); const imported = validateDocument(content.document ?? content); const namespace = uid('import'); const merged = mergeDocument(doc, imported, namespace); edit(merged); setDiagramId(merged.diagrams[doc.diagrams.length].id); setNotice(`Imported ${imported.diagrams.length} reusable diagrams`); });
  const undoEdit = () => { if (!undo.length || !doc) return; const last = undo[undo.length - 1]; setRedo(r => [doc, ...r]); setDoc(last); setUndo(undo.slice(0, -1)); setSelection(null); };
  const redoEdit = () => { if (!redo.length || !doc) return; setUndo(u => [...u, doc]); setDoc(redo[0]); setRedo(redo.slice(1)); setSelection(null); };
  if (!doc || !head || !diagram) return <div className="loading"><div className="brand-logo">A</div><h1>Atlas</h1><p>{error || 'Opening your architecture workspace…'}</p>{error && <button onClick={() => run(load)}>Retry</button>}</div>;
  const pending = proposals.filter(p => p.status === 'pending'); const totalChanges = changeSet.filter(c => c.kind !== 'layout').length;
  return <div className="app"><Markers/>
    <header className="topbar"><div className="brand"><span className="brand-logo">A</span><strong>atlas<span> / </span></strong><span className="workspace-name">{doc.name}</span></div><div className="top-actions"><span className={`save-state ${dirty || sourceDirty ? 'unsaved' : ''}`}><i/>{sourceDirty ? 'Source not applied' : dirty ? 'Unsaved changes' : 'All changes saved'}</span><button className="quiet" onClick={() => setModal('mcp')}>⌘ Connect agent</button><button className="primary" disabled={busy || !dirty || sourceDirty} onClick={() => { setInput(''); setModal('save'); }}>Save revision <span>↗</span></button></div></header>
    <div className="workspace"><aside className="library"><div className="section-label">WORKSPACE <span className="local-badge">LOCAL</span></div><button className="library-title" onClick={() => { setTab('canvas'); setReview(null); }}><span>▦</span> Architecture library</button>
      <div className="section-row"><span>DIAGRAMS <b>{doc.diagrams.length}</b></span><button aria-label="New diagram" title="New diagram" onClick={() => { setInput(''); setModal('new'); }}>+</button></div>
      <nav aria-label="Diagrams">{doc.diagrams.map(d => <button key={d.id} className={`diagram-link ${d.id === diagram.id ? 'active' : ''}`} onClick={() => navigate(d.id)}><span className="diagram-icon">{d.imports.length ? '▦' : '◇'}</span><span>{d.name}<small>{d.nodes.length} elements{d.imports.length ? ` · ${d.imports.length} references` : ''}</small></span></button>)}</nav>
      <button className="library-action" onClick={() => importRef.current?.click()} disabled={sourceDirty}>↥ Import project diagrams</button><input ref={importRef} type="file" accept=".json,.arch.json" hidden onChange={e => { if (e.target.files?.[0]) importFile(e.target.files[0]); e.target.value = ''; }}/>
      <div className="section-row proposal-heading"><span>AGENT PROPOSALS <b>{pending.length}</b></span><span className="live-dot"/></div>
      <div className="proposal-list">{pending.length ? pending.map(p => <button className="proposal-card" key={p.id} onClick={() => openProposal(p.id)}><span className="proposal-author">✦ {p.author}</span><strong>{p.rationale}</strong><small>{p.baseRevision === head.revision ? 'Ready to review' : 'Base revision is stale'} · {date(p.createdAt)}</small></button>) : <p className="muted empty-proposals">Agent proposals appear here for visual review.</p>}</div>
      <div className="section-row history-heading"><span>REVISION HISTORY</span></div><div className="history-list">{history.slice(0, 12).map((h, i) => <button key={h.revision} onClick={() => compareHistory(h.revision)}><span className={`history-dot ${i === 0 ? 'current' : ''}`}/><span><strong>{h.rationale}</strong><small>{h.author} · {date(h.createdAt)}</small></span></button>)}</div>
      <div className="library-footer"><button onClick={() => download(`${doc.id}.arch.json`, JSON.stringify(doc, null, 2))}>↓ Export project</button><button onClick={() => window.open('/uml-comparison.html', '_blank', 'noopener,noreferrer')}>◫ UML comparison</button><button onClick={() => setModal('help')}>? Syntax reference</button><span>Portable JSON · No cloud account</span></div>
    </aside>
    <main className="main"><div className="diagram-header"><div><div className="breadcrumb">Architecture library <span>/</span> {tab === 'review' ? 'Change review' : 'Diagram'}</div><h1>{tab === 'review' ? review?.label ?? 'Review your changes' : diagram.name}</h1></div><div className="diagram-count"><span>{diagram.nodes.length}</span> elements <i/> <span>{diagram.edges.length}</span> relationships</div></div>
      {remoteChanged && <div className="warning-banner">A newer revision is available. Your draft is preserved.<button onClick={() => { if (!dirty && !sourceDirty) run(load); else setError('Export or save your draft before reloading. A stale draft cannot overwrite the latest revision. Use Discard draft to reload.'); }}>Reload latest</button></div>}
      {error && <div className="error-banner" role="alert"><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError('')}>×</button></div>}
      <div className="viewbar"><div className="tabs" role="tablist" aria-label="Editor views">{(['canvas', 'uml', 'json', 'review'] as const).map(t => <button key={t} role="tab" aria-selected={tab === t} className={tab === t ? 'active' : ''} onClick={() => switchTab(t)}>{t === 'canvas' ? '▦  Canvas' : t === 'uml' ? '⌁  UML source' : t === 'json' ? '{ }  JSON' : `◫  Review${dirty ? ` · ${diffDocuments(head.document, doc).filter(c => c.kind !== 'layout').length}` : ''}`}</button>)}</div><div className="view-actions"><button title="Undo" aria-label="Undo" disabled={!undo.length || sourceDirty || tab === 'review'} onClick={undoEdit}>↶</button><button title="Redo" aria-label="Redo" disabled={!redo.length || sourceDirty || tab === 'review'} onClick={redoEdit}>↷</button>{(dirty || sourceDirty) && <button className="text-button" onClick={() => setModal('discard')}>Discard draft</button>}</div></div>
      {tab === 'canvas' && <div className="editor-body"><section className="canvas-wrap"><div className="canvas-toolbar"><div className="tool-group"><select aria-label="Element type" value={newKind} onChange={e => setNewKind(e.target.value as any)}>{nodeKinds.map(k => <option key={k}>{k}</option>)}</select><button onClick={addNode}>＋ Add element</button></div><div className="tool-divider"/><button onClick={() => { setEmbedTarget(doc.diagrams.find(d => d.id !== diagram.id)?.id ?? ''); setModal('embed'); }}>▦ Embed diagram</button><div className="tool-divider"/><select aria-label="New relationship type" title="Relationship created when connecting handles" value={relationship} onChange={e => setRelationship(e.target.value as any)}>{edgeKinds.map(k => <option key={k}>{k}</option>)}</select></div>
        <Canvas key={diagram.id} document={doc} diagram={diagram} focusId={selection?.id} onSelect={(kind, id) => setSelection({ kind, id })} onMove={(kind, id, position) => editDiagram({ ...diagram, ...(kind === 'node' ? { nodes: diagram.nodes.map(n => n.id === id ? { ...n, position } : n) } : { imports: diagram.imports.map(i => i.id === id ? { ...i, position } : i) }) })} onConnect={connect} onOpen={navigate} onExpand={expand}/><div className="canvas-hint">Drag to arrange · Connect the side handles · Select to inspect</div>
      </section><aside className="inspector"><div className="section-label">{selection ? 'ELEMENT PROPERTIES' : 'DIAGRAM PROPERTIES'}{selection && <button aria-label="Close inspector selection" onClick={() => setSelection(null)}>×</button>}</div>
        {selectedNode ? <><div className="inspector-title"><span className={`property-icon property-${selectedNode.kind}`}>{selectedNode.kind === 'actor' ? '♙' : selectedNode.kind === 'note' ? '·' : `«${selectedNode.stereotype || selectedNode.kind}»`}</span><div><h2>{selectedNode.label || 'Untitled element'}</h2><code>{selectedNode.id}</code></div></div><Field label="Name"><input value={selectedNode.label} onChange={e => updateNode({ label: e.target.value })}/></Field><Field label="UML element"><select value={selectedNode.kind} onChange={e => updateNode({ kind: e.target.value as any })}>{nodeKinds.map(k => <option key={k}>{k}</option>)}</select></Field><Field label="Stereotype"><input placeholder="e.g. boundary" value={selectedNode.stereotype} onChange={e => updateNode({ stereotype: e.target.value })}/></Field><Field label="Responsibility"><textarea rows={4} value={selectedNode.description} placeholder="What does this element own?" onChange={e => updateNode({ description: e.target.value })}/></Field><Field label="Members · one per line"><textarea className="mono" rows={4} placeholder={'+operation(): Result\n-field: Type'} value={selectedNode.members.join('\n')} onChange={e => updateNode({ members: e.target.value ? e.target.value.split('\n') : [] })}/></Field>
          <div className="inspector-section"><h3>Code regions</h3><button onClick={() => updateNode({ codeLinks: [...selectedNode.codeLinks, { path: '', startLine: 1 }] })}>＋ Link</button></div>{selectedNode.codeLinks.map((link, i) => <div className="code-link" key={i}><input aria-label="Code file path" placeholder="src/module.ts" value={link.path} onChange={e => updateNode({ codeLinks: selectedNode.codeLinks.map((l, j) => j === i ? { ...l, path: e.target.value } : l) })}/><div className="line-inputs"><label>From<input type="number" min={1} value={link.startLine} onChange={e => updateNode({ codeLinks: selectedNode.codeLinks.map((l, j) => j === i ? { ...l, startLine: Number(e.target.value) } : l) })}/></label><label>To<input type="number" min={link.startLine} value={link.endLine ?? ''} onChange={e => updateNode({ codeLinks: selectedNode.codeLinks.map((l, j) => j === i ? { ...l, endLine: e.target.value ? Number(e.target.value) : undefined } : l) })}/></label><button title="Read code region" aria-label="Read code region" onClick={() => run(async () => setCodePreview(await api(`/code?${new URLSearchParams({ path: link.path, startLine: String(link.startLine), ...(link.endLine ? { endLine: String(link.endLine) } : {}) })}`)))}>↗</button><button aria-label="Remove code link" onClick={() => updateNode({ codeLinks: selectedNode.codeLinks.filter((_, j) => i !== j) })}>×</button></div></div>)}{!selectedNode.codeLinks.length && <p className="muted">Link this element to lines in any language.</p>}
          <div className="inspector-section"><h3>Code / pseudocode</h3></div><input aria-label="Snippet language" placeholder="pseudocode" value={selectedNode.snippet?.language ?? ''} onChange={e => updateNode({ snippet: { language: e.target.value, code: selectedNode.snippet?.code ?? '' } })}/><textarea aria-label="Code snippet" className="mono snippet" rows={7} placeholder="Describe the behavior…" value={selectedNode.snippet?.code ?? ''} onChange={e => updateNode({ snippet: { language: selectedNode.snippet?.language || 'pseudocode', code: e.target.value } })}/><button className="danger delete-element" onClick={removeSelection}>Delete element</button></>
        : selectedEdge ? <><h2>Relationship</h2><code>{selectedEdge.id}</code><Field label="Label"><input value={selectedEdge.label} onChange={e => updateEdge({ label: e.target.value })}/></Field><Field label="Relationship type"><select value={selectedEdge.kind} onChange={e => updateEdge({ kind: e.target.value as any })}>{edgeKinds.map(k => <option key={k}>{k}</option>)}</select></Field>{(['source', 'target'] as const).map(field => <Field key={field} label={field}><select value={selectedEdge[field]} onChange={e => updateEdge({ [field]: e.target.value })}>{[...diagram.nodes, ...diagram.imports].map(n => <option key={n.id} value={n.id}>{n.label}</option>)}</select></Field>)}<Field label="Source multiplicity"><input placeholder="1" value={selectedEdge.sourceMultiplicity} onChange={e => updateEdge({ sourceMultiplicity: e.target.value })}/></Field><Field label="Target multiplicity"><input placeholder="0..*" value={selectedEdge.targetMultiplicity} onChange={e => updateEdge({ targetMultiplicity: e.target.value })}/></Field><button className="danger delete-element" onClick={removeSelection}>Delete relationship</button></>
        : selectedImport ? <><h2>Reusable diagram</h2><code>{selectedImport.id}</code><Field label="Label in this diagram"><input value={selectedImport.label} onChange={e => updateImport({ label: e.target.value })}/></Field><p>This reference uses <strong>{doc.diagrams.find(d => d.id === selectedImport.diagramId)?.name}</strong>. Changes to that diagram appear everywhere it is embedded.</p><button className="primary full" onClick={() => navigate(selectedImport.diagramId)}>Open source diagram ↗</button><button className="full" onClick={() => expand(selectedImport.id)}>{selectedImport.expanded ? 'Collapse reference' : 'Expand on canvas'}</button><button className="danger delete-element" onClick={removeSelection}>Remove reference</button></>
        : <><div className="inspector-title"><span className="property-icon">◇</span><div><h2>{diagram.name}</h2><code>{diagram.id}</code></div></div><Field label="Diagram name"><input value={diagram.name} onChange={e => editDiagram({ ...diagram, name: e.target.value })}/></Field><Field label="Purpose"><textarea rows={6} value={diagram.description} onChange={e => editDiagram({ ...diagram, description: e.target.value })}/></Field><div className="inspector-callout"><span>↗</span><h3>One design, two ways to edit</h3><p>Arrange elements here or edit UML source. Stable IDs keep visual, text, and agent changes connected.</p></div><div className="inspector-section"><h3>Diagram actions</h3></div><button className="full" onClick={() => download(`${diagram.id}.puml`, toUml(diagram), 'text/plain')}>↓ Export UML source</button><button className="full" onClick={() => { const clone = { ...structuredClone(diagram), id: uid('diagram'), name: `${diagram.name} copy` }; edit({ ...doc, diagrams: [...doc.diagrams, clone] }); setDiagramId(clone.id); }}>Duplicate diagram</button><button className="danger full" disabled={doc.diagrams.length === 1} onClick={() => { try { const candidate = validateDocument({ ...doc, diagrams: doc.diagrams.filter(d => d.id !== diagram.id) }); edit(candidate); setDiagramId(candidate.diagrams[0].id); } catch { setError('This diagram is embedded elsewhere. Remove its references before deleting it.'); } }}>Delete diagram</button></>}
      </aside></div>}
      {(tab === 'uml' || tab === 'json') && <div className="source-view"><div className="source-editor"><div className="source-toolbar"><span>{diagram.id}.{tab === 'uml' ? 'puml' : 'json'}</span><div><button disabled={!sourceDirty} onClick={() => { setSourceDirty(false); setError(''); }}>Discard source edits</button><button className="primary" disabled={!sourceDirty} onClick={applySource}>Apply to diagram</button></div></div><textarea aria-label={tab === 'uml' ? 'UML source editor' : 'JSON diagram editor'} spellCheck={false} value={source} onChange={e => { setSource(e.target.value); setSourceDirty(true); }}/><div className="source-status">{source.split('\n').length} lines · {sourceDirty ? 'Unapplied source edits' : 'In sync with canvas'} · {tab === 'uml' ? 'Atlas UML subset' : 'Schema version 1'}</div></div><div className="source-preview"><div className="preview-label">{sourceDirty ? 'LAST APPLIED DIAGRAM' : 'LIVE DIAGRAM'}</div><Canvas key={`source_${diagram.id}`} document={doc} diagram={diagram} onOpen={navigate} readOnly/></div></div>}
      {tab === 'review' && reviewBase && reviewDoc && <div className="review-view"><div className="review-summary"><div><div className="review-badges"><span className="added">+ {changeSet.filter(c => c.kind === 'added').length} added</span><span className="removed">− {changeSet.filter(c => c.kind === 'removed').length} removed</span><span className="modified">Δ {changeSet.filter(c => c.kind === 'modified').length} modified</span><span>{changeSet.filter(c => c.kind === 'layout').length} layout</span></div><p>{review?.rationale ?? 'Compare your local draft with the last saved revision.'}</p></div>{review?.proposal && <div className="review-buttons"><span>{review.proposal.status === 'pending' && review.proposal.baseRevision !== head.revision ? 'Stale proposal · ask the agent to refresh' : review.proposal.status}</span><button disabled={busy || review.proposal.status !== 'pending'} onClick={() => reviewProposal('reject')}>Reject</button><button className="primary" disabled={busy || dirty || review.proposal.status !== 'pending' || review.proposal.baseRevision !== head.revision} title={dirty ? 'Save or discard your draft first' : 'Accept this architecture change'} onClick={() => reviewProposal('accept')}>Accept proposal</button></div>}</div>
        <div className="review-canvases"><div><div className="compare-heading"><span className="dot-before"/> BEFORE <select aria-label="Diagram to compare" value={reviewDiagram?.id ?? ''} onChange={e => setDiagramId(e.target.value)}>{Array.from(new Map([...reviewBase.diagrams, ...reviewDoc.diagrams].map(d => [d.id, d])).values()).map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></div>{beforeDiagram ? <Canvas key={`before_${beforeDiagram.id}_${review?.proposal?.id || ''}`} document={reviewBase} diagram={beforeDiagram} readOnly changes={changeSet} focusId={focus} onOpen={navigate}/> : <div className="missing-diagram">Diagram did not exist</div>}</div><div><div className="compare-heading"><span className="dot-after"/> AFTER <span>{afterDiagram?.name ?? 'Removed diagram'}</span></div>{afterDiagram ? <Canvas key={`after_${afterDiagram.id}_${review?.proposal?.id || ''}`} document={reviewDoc} diagram={afterDiagram} readOnly changes={changeSet} focusId={focus} onOpen={navigate}/> : <div className="missing-diagram">Diagram removed</div>}</div></div>
        <div className="changes-panel"><div className="changes-heading"><h2>{totalChanges ? `${totalChanges} design changes` : 'No design changes'}</h2><label><input type="checkbox" checked={showLayout} onChange={e => setShowLayout(e.target.checked)}/> Include layout</label><button onClick={() => download('architecture-diff.json', JSON.stringify(changeSet, null, 2))}>↓ Export diff</button></div><div className="changes-list">{changeSet.filter(c => showLayout || c.kind !== 'layout').map((c, i) => <details key={`${c.diagramId}-${c.entity}-${c.id}-${i}`} className={`change-row ${c.kind}`}><summary onClick={() => { if (c.diagramId) setDiagramId(c.diagramId); setFocus(c.id); }}><span className="change-symbol">{c.kind === 'added' ? '+' : c.kind === 'removed' ? '−' : c.kind === 'layout' ? '↔' : 'Δ'}</span><strong>{c.label}</strong><span className="change-entity">{c.entity}</span><span>{c.kind === 'modified' || c.kind === 'layout' ? c.fields.join(', ') : c.kind}</span><code>{c.diagramId}{c.diagramId ? '/' : ''}{c.id}</code></summary><div className="change-detail"><pre>{JSON.stringify(c.before, null, 2) ?? '(not present)'}</pre><pre>{JSON.stringify(c.after, null, 2) ?? '(not present)'}</pre></div></details>)}{!changeSet.length && <p className="muted no-changes">This architecture matches the comparison revision. Edit a diagram or open an agent proposal to see a diff.</p>}</div></div>
      </div>}
    </main></div>
    <footer className="statusbar"><span><i className="live-dot"/> Local workspace <span className="status-path" title={workspacePath}>{workspacePath}</span></span><span>JSON schema v1 <b>·</b> revision {head.revision.slice(0, 8)} <b>·</b> Atlas 0.1</span></footer>
    {notice && <div className="toast" role="status">✓ {notice}</div>}
    {modal && <div className="modal-backdrop" onClick={() => setModal(null)}><section className={`modal ${modal === 'help' || modal === 'mcp' ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e => e.stopPropagation()} onKeyDown={e => { if (e.key === 'Escape') setModal(null); }}>{error && <div className="dialog-error" role="alert">{error}</div>}<button className="modal-close" aria-label="Close dialog" onClick={() => setModal(null)}>×</button>
      {modal === 'discard' && <><div className="eyebrow">LOCAL DRAFT</div><h2 id="modal-title">Discard unsaved changes?</h2><p>Your saved revisions are preserved. This reloads the latest saved architecture and removes your unsaved model and source edits.</p><div className="modal-actions"><button onClick={() => setModal(null)}>Keep editing</button><button className="danger" disabled={busy} onClick={() => run(async () => { await load(); setModal(null); setNotice('Latest saved architecture loaded'); })}>Discard draft</button></div></>}
      {modal === 'save' && <><div className="eyebrow">VERSION HISTORY</div><h2 id="modal-title">Save an architecture revision</h2><p>Record what changed and why, so people and agents share the same context.</p><Field label="Author"><input value={author} onChange={e => setAuthor(e.target.value)}/></Field><Field label="Change rationale"><textarea autoFocus rows={4} placeholder="What changed, and why?" value={input} onChange={e => setInput(e.target.value)}/></Field><div className="modal-actions"><button onClick={() => setModal(null)}>Cancel</button><button className="primary" disabled={busy || !input.trim() || !author.trim()} onClick={save}>Save revision</button></div></>}
      {modal === 'new' && <><div className="eyebrow">ARCHITECTURE LIBRARY</div><h2 id="modal-title">Create a diagram</h2><Field label="Diagram name"><input autoFocus value={input} placeholder="e.g. Payment boundary" onChange={e => setInput(e.target.value)}/></Field><div className="modal-actions"><button onClick={() => setModal(null)}>Cancel</button><button className="primary" disabled={!input.trim() || sourceDirty} onClick={() => { const d: Diagram = { id: uid('diagram'), name: input.trim(), description: '', nodes: [], edges: [], imports: [] }; edit({ ...doc, diagrams: [...doc.diagrams, d] }); setDiagramId(d.id); setSelection(null); setModal(null); setTab('canvas'); }}>Create diagram</button></div></>}
      {modal === 'embed' && <><div className="eyebrow">REUSABLE ARCHITECTURE</div><h2 id="modal-title">Embed a diagram</h2><p>Reference a part within this whole. You can expand it on the canvas or open its source. Import cycles are rejected.</p><Field label="Source diagram"><select value={embedTarget} onChange={e => setEmbedTarget(e.target.value)}><option value="">Choose a diagram</option>{doc.diagrams.filter(d => d.id !== diagram.id).map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><div className="modal-actions"><button onClick={() => setModal(null)}>Cancel</button><button className="primary" disabled={!embedTarget} onClick={() => { try { const reference = { id: uid('ref'), diagramId: embedTarget, label: doc.diagrams.find(d => d.id === embedTarget)!.name, position: { x: 400, y: 300 }, expanded: false }; const next = validateDocument({ ...doc, diagrams: doc.diagrams.map(d => d.id === diagram.id ? { ...d, imports: [...d.imports, reference] } : d) }); edit(next); setSelection({ kind: 'import', id: reference.id }); setModal(null); } catch (e) { setError((e as Error).message); setModal(null); } }}>Embed diagram</button></div></>}
      {modal === 'help' && <><div className="eyebrow">ATLAS UML · VERSION 1</div><h2 id="modal-title">A readable, round-trip design language</h2><p>Use a structural subset of PlantUML-style syntax. Atlas-specific metadata lives in comments. Unsupported syntax produces a line error.</p><pre className="help-code">{'@startuml overview\ntitle Checkout architecture\n\ncomponent "Checkout API" as api\ninterface "Payment gateway" as gateway\nclass "Order" as order {\n  +id: UUID\n  +submit(): Result\n}\n\napi ..> gateway : "authorize"\napi --> order : "creates"\n@enduml'}</pre><div className="syntax-grid"><span><code>--&gt;</code> association</span><span><code>..&gt;</code> dependency</span><span><code>--|&gt;</code> generalization</span><span><code>..|&gt;</code> realization</span><span><code>*--</code> composition</span><span><code>o--</code> aggregation</span><span><code>-&gt;</code> transition</span></div><p><strong>Elements:</strong> {nodeKinds.join(', ')}.</p><p><code>' @node</code> preserves positions, descriptions, members’ context, code links and snippets. <code>' @edge</code> preserves relationship IDs and multiplicities. <code>' @import</code> references another diagram by ID.</p><p className="muted">Full UML 2.5, PlantUML preprocessing, sequence diagrams, and automatic code synchronization are outside this first version. Package elements are graph nodes; reusable diagram references provide containment.</p></>}
      {modal === 'mcp' && <><div className="eyebrow">BIDIRECTIONAL DESIGN</div><h2 id="modal-title">Connect any MCP agent</h2><p>Launch the Atlas stdio server in your agent’s MCP configuration. Point the workspace at the same project opened here.</p><pre className="help-code">{JSON.stringify(mcpConfig, null, 2)}</pre><p>This configuration uses the Node executable and Atlas installation that are running now. Add it to your agent’s MCP settings; no global installation is needed. For another project, change the workspace argument.</p><ol><li>Ask the agent to call <code>get_architecture</code>.</li><li>Design together, then call <code>propose_diagram</code> or <code>propose_architecture</code> with a rationale and base revision.</li><li>Open the proposal here, inspect its visual diff, and accept or reject it.</li></ol><p className="muted">The agent can read and propose. Acceptance happens in this studio. The editor checks for new proposals every four seconds.</p><button onClick={() => { navigator.clipboard.writeText(JSON.stringify(mcpConfig, null, 2)).then(() => setNotice('MCP configuration copied')).catch(() => setError('Clipboard unavailable. Select and copy the configuration.')); }}>Copy configuration</button></>}
    </section></div>}
    {codePreview && <div className="modal-backdrop" onClick={() => setCodePreview(null)}><section className="modal wide code-modal" role="dialog" aria-modal="true" aria-label="Code region" onClick={e => e.stopPropagation()}><button className="modal-close" aria-label="Close code preview" onClick={() => setCodePreview(null)}>×</button><div className="eyebrow">LINKED CODE REGION</div><h2>{codePreview.path}</h2><p>Lines {codePreview.startLine}–{codePreview.endLine} · read only</p><pre>{codePreview.code.split('\n').map((line, i) => <div key={i}><span className="line-number">{codePreview.startLine + i}</span>{line || ' '}</div>)}</pre></section></div>}
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span>{children}</label>; }
